name: build

on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare Environment
        run: |
          ./.github/workflows/install_gtest.sh
          ./.github/workflows/install_gbench.sh
          ./dependencies.sh
      - name: Build Reindexer
        run: |
          export CPLUS_INCLUDE_PATH=$GITHUB_WORKSPACE/grpc/third_party/abseil-cpp
          mkdir build && cd build
          cmake ..
          make -j8
      - name: 'C++ tests'
        run: |
          echo "Running C++ directly in this job due to Action's problem with artifacts transition for macos-11 and macos-12 runners"
          cd build
          ./cpp_src/gtests/tests/tests --gtest_filter="FTGenericApi.ConfigFtProc*" --gtest_repeat=10

